package day05;
/*try블럭 하나에 catch절은 여러개 올 수 있다.
 * 그러나 이때 catch순서를 주의해야한다.
 * -부모자식의 상속관계가 있는 예외일 경우
 * 	자식을 먼저 catch하고 부모 예외를 나중에 catch해야한다.
 **/
public class ExceptionTest4 {

	public static void main(String[] args) {
		//args : String타입의 배열, 명령줄 인수
		//컴파일 : javac ExceptionTest4.java
		//실행 : java ExceptionTest4 안녕 잘가
		//						args[0] args[1]
		try {
			System.out.println("국어= "+args[0]);//국어
			System.out.println("영어= "+args[1]);//영어
			//총 합계 점수를 구해 출력하세요
			//평균점수 구해 출력하세요
			System.out.println("-------------------------");
			System.out.println("총점: "+(args[0]+args[1]));
			System.out.println("-------------------------");
			//java.lang.Integer클래스==>Wrapper class
			//int(기본자료형) ===> Integer
			//public static int parseIn(String s):
			//문자열 s를 정수로 변환시켜 반환해주는 메소드
			//총점
			//평균점수
			int kor=Integer.parseInt(args[0]);//NumberFormatException
			int eng=Integer.parseInt(args[1]);
			int sum=kor+eng;
			int avg=sum/args.length;
			
			System.out.println("총점: "+sum);
			System.out.println("평균: "+avg);
			System.out.println(avg/0);//ArithmeticException
			
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("명령줄 인수를 입력해야 합니다!");
		}catch(NumberFormatException e) {
			System.out.println("정수는 숫자로 입력해야 해요!");
		}catch(Exception e) {
			System.out.println("기타 예상치 못한 예외 발생"+e);
		}
		
	}//main----

}//class-----------
